### ISSUE TITLE
Dead link on humio/kubernetes2humio

### ISSUE THREAD

**Issue by StianOvrevage** [humio/docs.humio.com#69]
There is a link on https://github.com/humio/kubernetes2humio pointing to https://docs.humio.com/sending_logs_to_humio/integrations/kubernetes/ , which gives a 404.

**Comment by mwl** [comment]
Thanks for reporting. I've restored the old url.

**Comment by mwl** [comment]
@StianOvrevage Wait a minute. How did you end up on that repo anyway?

**Comment by StianOvrevage** [comment]
It's the #1 hit if you Google "Humio Kubernetes"
